### ISSUE TITLE
MineSuperior has been faking its playercount for almost a month (+ Minecraft Central's playercount looks suspicious?)

### ISSUE THREAD

**Issue by 5imGitHub** [clrxbl/blockgametracker#23]
So, I don't know if this tracker is fine with tracking servers that have fake playercounts, but I noticed that for almost a month, MineSuperior has been faking its playercount to look like it gets 2k+ concurrent players online, when in reality it only has like 200 or less concurrent players online.
Here's a screenshot of MineSuperior averaging 100-200 concurrent players online, and then suddenly starts averaging 1500-2500 concurrent players online:
![MS1](https://github.com/clrxbl/blockgametracker/assets/123900464/6f3f3657-7009-437d-b860-b09c6767a6ce)
And here's a screenshot of MineSuperior's real playercount when you put it in the server list:
![MS2](https://github.com/clrxbl/blockgametracker/assets/123900464/3d5004cf-b569-4583-a267-8d69baa728c3)

I also noticed that Minecraft Central's playercount looks suspicious. It always gets 1000-1200 concurrent players online, but it has never gone below 1k concurrent players online, so maybe Minecraft Central also fakes playercount? But this is mostly suspicion, so I don't know if it actually does fake playercount.
Here's a screenshot of Minecraft Central never going below 1k players in the past 6 months:
![MCCe](https://github.com/clrxbl/blockgametracker/assets/123900464/055dc6ae-0bc8-4325-b572-d1af407e7baa)

**Comment by clrxbl** [comment]
You're definitely right about MC Central which I did find odd since day 1 but mostly added them since they're an old server and have been on the original Minetrack (if I can remember properly).

MineSuperior spoofing on BGT is not intentional and I'll sort that one out with the owner.
