### ISSUE TITLE
[Suggestion] Add an "all" Edition to display both "java" and "bedrock" servers at once.

### ISSUE THREAD

**Issue by 5imGitHub** [clrxbl/blockgametracker#24]
To more easily compare Java servers with Bedrock servers, and I think it would also kind of make sense since there are a few servers with the "java" Edition tag that have Java&Bedrock crossplay (with Minehut and DonutSMP being the biggest two that have it).

**Comment by clrxbl** [comment]
Bedrock servers on BGT are all partnered servers only.

Java servers on BGT are servers that may accept Bedrock connections but more importantly are pre-dominantly active within the Java community. I don't currently see a need to differentiate between crossplay servers and non-crossplay servers. Not to mention what would you do with historical data when a server suddenly adds crossplay support to their server? (and how would I keep track of it without keeping an eye out on every server?)
